baseURL = "https://romanv.dev/"
title = "Роман Васильченко — Go Backend Engineer"
theme = "PaperMod"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[pagination]
  pagerSize = 10

[params]
  env = "production"
  title = "Роман Васильченко"
  description = "Go Backend Engineer из Астаны. Высоконагруженные микросервисы, gRPC/REST API, PostgreSQL/Elastic, Kafka, мониторинг и алертинг."
  keywords = ["Go", "Golang", "Backend", "Microservices", "gRPC", "REST", "PostgreSQL", "Kafka", "ElasticSearch", "Prometheus", "Grafana", "Resume", "Blog", "Астана", "Казахстан", "Ozon"]
  author = "Роман Васильченко"

  # Optimized settings
  DateFormat = "02.01.2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  showReadingTime = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  hideFooter = false
  showPostNavLinks = true
  showRssButtonInSectionTermPages = true
  ShowShareButtons = true
  ShowToc = true
  TocOpen = false
  comments = false
  mainSections = ["posts"]

  # Performance
  disableFingerprinting = false
  disableScrollToTop = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.profileMode]
    enabled = true
    title = "Роман Васильченко"
    subtitle = "Go Backend Engineer • Астана, Казахстан"
    imageUrl = "/images/avatar.png"
    imageTitle = "Роман Васильченко"
    imageWidth = 160
    imageHeight = 160

  [params.homeInfoParams]
    Title = "Go Backend • Микросервисы • Observability"
    Content = "Высоконагруженные Go-сервисы, gRPC/REST API, PostgreSQL/Kafka/Elastic, Prometheus/Grafana мониторинг. Опыт в Ozon, создание pet-проектов для борьбы с коррупцией."

  [params.cover]
    linkFullImages = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4

  [[params.socialIcons]]
    name = "email"
    url = "mailto:roman.vassilchenko.work@gmail.com"
    title = "Email"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/RomanVassilchenko"
    title = "GitHub"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rovassilchenko/"
    title = "LinkedIn"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/Roman_Vassilchenko"
    title = "Telegram"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
