baseURL = "https://romanv.dev/"
theme = "PaperMod"
defaultContentLanguage = "ru"
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[languages]
  [languages.ru]
    languageCode = "ru-ru"
    languageName = "Русский"
    title = "Роман Васильченко — Go Backend Engineer"
    weight = 1

    [languages.ru.params]
      title = "Роман Васильченко"
      description = "Go Backend Engineer из Астаны. Высоконагруженные микросервисы, gRPC/REST API, PostgreSQL/Elastic, Kafka, мониторинг и алертинг."
      keywords = ["Go", "Golang", "Backend", "Microservices", "gRPC", "REST", "PostgreSQL", "Kafka", "ElasticSearch", "Prometheus", "Grafana", "Resume", "Blog", "Астана", "Казахстан", "Ozon"]
      author = "Роман Васильченко"

      [languages.ru.params.profileMode]
        enabled = true
        title = "Роман Васильченко"
        subtitle = "Go Backend Engineer • Астана, Казахстан (GMT+5)"
        imageUrl = "/images/avatar.png"
        imageTitle = "Роман Васильченко"
        imageWidth = 160
        imageHeight = 160
        buttons = [
          {name = "Резюме", url = "/resume/ru.pdf", target = "_blank"}
        ]

      [languages.ru.params.homeInfoParams]
        Title = "Go Backend • Микросервисы • Observability"
        Content = "Высоконагруженные Go-сервисы, gRPC/REST API, PostgreSQL/Kafka/Elastic, Prometheus/Grafana мониторинг. Опыт в Ozon, создание pet-проектов для борьбы с коррупцией."

  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    title = "Roman Vassilchenko — Go Backend Engineer"
    weight = 2

    [languages.en.params]
      title = "Roman Vassilchenko"
      description = "Go Backend Engineer from Astana. High-load microservices, gRPC/REST API, PostgreSQL/Elastic, Kafka, monitoring and alerting."
      keywords = ["Go", "Golang", "Backend", "Microservices", "gRPC", "REST", "PostgreSQL", "Kafka", "ElasticSearch", "Prometheus", "Grafana", "Resume", "Blog", "Astana", "Kazakhstan", "Ozon"]
      author = "Roman Vassilchenko"

      [languages.en.params.profileMode]
        enabled = true
        title = "Roman Vassilchenko"
        subtitle = "Go Backend Engineer • Astana, Kazakhstan (GMT+5)"
        imageUrl = "/images/avatar.png"
        imageTitle = "Roman Vassilchenko"
        imageWidth = 160
        imageHeight = 160
        buttons = [
          {name = "Resume", url = "/resume/en.pdf", target = "_blank"}
        ]

      [languages.en.params.homeInfoParams]
        Title = "Go Backend • Microservices • Observability"
        Content = "High-load Go services, gRPC/REST API, PostgreSQL/Kafka/Elastic, Prometheus/Grafana monitoring. Experience at Ozon, creating pet projects to fight corruption."

[minify]
  disableXML = true
  minifyOutput = true

[pagination]
  pagerSize = 10

[params]
  env = "production"

  # Optimized settings
  DateFormat = "02.01.2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  showReadingTime = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  hideFooter = false
  showPostNavLinks = true
  showRssButtonInSectionTermPages = true
  ShowShareButtons = true
  ShowToc = true
  TocOpen = false
  comments = false
  mainSections = ["posts"]

  # Performance
  disableFingerprinting = false
  disableScrollToTop = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"


  [params.cover]
    linkFullImages = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4

  [[params.socialIcons]]
    name = "email"
    url = "mailto:roman.vassilchenko.work@gmail.com"
    title = "Email"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/RomanVassilchenko"
    title = "GitHub"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rovassilchenko/"
    title = "LinkedIn"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/Roman_Vassilchenko"
    title = "Telegram"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
