export const personal = {
  phone: '+7 775 900-46-26',
  email: 'roman.vassilchenko.work@gmail.com',
  website: 'romanv.dev',
  github: 'github.com/RomanVassilchenko',
  linkedin: 'linkedin.com/in/rovassilchenko',
  telegram: 't.me/Roman_Vassilchenko',
}

export const resumes = {
  en: {
    name: 'Roman Vassilchenko',
    role: 'Go Backend Engineer',
    location: 'Astana, Kazakhstan · UTC+5',
    summary:
      'I build backend systems that accelerate critical business workflows and stay reliable under load, from credit pipelines at Bereke Bank to company-wide platforms at Ozon.',
    labels: {
      contacts: 'Contacts',
      impact: 'Selected impact',
      experience: 'Experience',
      project: 'Selected project',
      toolkit: 'Skills',
      education: 'Education',
      languages: 'Languages',
      additional: 'Availability',
    },
    metrics: [
      { value: '>2.5×', label: 'faster auto-loan issuance', note: '40 to 15 minutes' },
      { value: '25%', label: 'faster employee data access', note: 'dedicated data service' },
      { value: '3×', label: 'faster candidate search', note: 'p95 down to 500-850 ms' },
    ],
    skills: [
      { label: 'Backend', value: 'Go, gRPC, REST/HTTP, GraphQL, Protocol Buffers' },
      { label: 'Data', value: 'PostgreSQL, Redis, ClickHouse, Vertica, Elasticsearch, MinIO/S3' },
      { label: 'Distributed', value: 'Kafka, Camunda BPMN, microservices, event-driven systems' },
      {
        label: 'Operations',
        value: 'Docker, Kubernetes, Grafana, Prometheus, GitHub Actions, Linux',
      },
    ],
    experience: [
      {
        company: 'Bereke Bank',
        role: 'Middle Golang Developer',
        period: 'Sep 2025 · Present',
        context: 'Auto Loan Issuance / Unified Credit Pipeline · high load · event driven',
        items: [
          "Architect and build the company's <strong>unified credit pipeline</strong>, standardizing loan issuance across products and centralizing application routing and validation.",
          'Built numerous <strong>production integrations</strong> with government and financial services, including First Credit Bureau, collateral registries and identity verification.',
          'Designed fault-tolerant microservice architecture with strict <strong>latency SLA</strong> and event-driven communication via Kafka.',
          'Supported the auto-loan pipeline from pilot to production: parallelized processing, made issuance <strong>more than 2.5× faster</strong>, from 40 to 15 minutes, and grew volume to <strong>130 applications per day within six months</strong>.',
          'Built a corporate messenger alerting library and operational notifications for production workflows.',
        ],
        stack: ['Go', 'PostgreSQL', 'Redis', 'Kafka', 'Camunda BPMN', 'Docker', 'GraphQL', 'REST'],
      },
      {
        company: 'Ozon Tech',
        role: 'Junior Go Backend Engineer',
        period: 'Aug 2024 · Sep 2025',
        context: 'Employee platform · 3-person backend team · on-call ownership',
        items: [
          'Co-designed the split of a large monolith into roughly <strong>10 domain services</strong>; built the employee-data service and cut average lookup time by <strong>25%</strong>.',
          'Sole backend owner of recurring compliance-questionnaire workflows, including employee assignment, notifications and legal administration.',
          'Automated attendance and seat reclamation for <strong>10K+ employees</strong>; the platform sustained <strong>2,000 concurrent users</strong> during rollout.',
          'Built a trademark-approval backend and Go document generator; also delivered analytics exports and video-preview workflows for files up to <strong>2 TB</strong>.',
        ],
        stack: ['Go', 'gRPC', 'PostgreSQL', 'ClickHouse', 'Redis', 'Kafka', 'Vertica', 'Grafana'],
      },
      {
        company: 'Ozon Tech',
        role: 'Go Backend Intern',
        period: 'Dec 2023 · Aug 2024',
        context: 'Company-wide hiring platform · 4-person backend team · on-call',
        items: [
          'Cut candidate-search p95 from <strong>1.5-2 s to 500-850 ms</strong> by fixing SQL indexes and rewriting Elasticsearch queries, verified through repeated load tests.',
          'Designed and built a candidate-update notification bot with reliable delayed delivery through Kafka.',
          'Joined the on-call rotation, resolved long-standing production defects and built Grafana dashboards for funnel anomalies and system errors.',
        ],
        stack: [
          'Go',
          'PostgreSQL',
          'Redis',
          'Elasticsearch',
          'Kafka',
          'ClickHouse',
          'gRPC',
          'Grafana',
        ],
      },
    ],
    project: {
      role: 'Creator · Backend engineer',
      name: 'AdalQarau',
      subtitle: 'Public procurement analytics platform',
      period: '2024 · Present',
      items: [
        'Built rule-based corruption-risk detection across <strong>15M+ contracts</strong>, 197K buyers and 800K suppliers using eight indicator algorithms without labeled training data.',
        'Produced <strong>448K risk flags</strong> across all 20 regions of Kazakhstan; thresholds were calibrated with government auditors and used in real audit workflows.',
      ],
      stack: [
        'Go',
        'ConnectRPC',
        'PostgreSQL',
        'React',
        'TypeScript',
        'MinIO/S3',
        'Docker',
        'Protobuf',
      ],
    },
    education: [
      {
        degree: 'M.Sc. Computer Science & Engineering',
        school: 'Astana IT University',
        period: '2025 · Present',
        note: 'Research: intelligent methods for anomaly detection in tender procurement data.',
        masters: true,
      },
      {
        degree: 'B.Sc. Software Engineering',
        school: 'Astana IT University',
        period: '2023 · 2025',
      },
      {
        degree: 'Previous studies',
        school: 'ITMO University, St. Petersburg',
        period: '2021 · 2023',
        note: 'Two years completed before transferring to AITU.',
      },
    ],
    languages: ['Russian · Native', 'English · C1 professional', 'Kazakh · Basic'],
    additional: ['Full-time · office / hybrid / remote', 'Ready to relocate'],
  },
  ru: {
    name: 'Роман Васильченко',
    role: 'Go Backend-разработчик',
    location: 'Астана, Казахстан · UTC+5',
    summary:
      'Создаю backend-системы, которые ускоряют ключевые бизнес-процессы и стабильно работают под высокой нагрузкой: от кредитных конвейеров в Bereke Bank до корпоративных платформ Ozon.',
    labels: {
      contacts: 'Контакты',
      impact: 'Ключевые результаты',
      experience: 'Опыт работы',
      project: 'Проект',
      toolkit: 'Навыки',
      education: 'Образование',
      languages: 'Языки',
      additional: 'Формат работы',
    },
    metrics: [
      { value: '>2,5×', label: 'быстрее выдача автокредита', note: 'с 40 до 15 минут' },
      {
        value: '25%',
        label: 'быстрее доступ к данным сотрудников',
        note: 'отдельный сервис данных',
      },
      {
        value: '3×',
        label: 'быстрее поиск кандидатов',
        note: 'p95 сокращён до 500-850 мс',
      },
    ],
    skills: [
      { label: 'Backend', value: 'Go, gRPC, REST/HTTP, GraphQL, Protocol Buffers' },
      { label: 'Данные', value: 'PostgreSQL, Redis, ClickHouse, Vertica, Elasticsearch, MinIO/S3' },
      {
        label: 'Распределённые системы',
        value: 'Kafka, Camunda BPMN, микросервисы, event-driven архитектура',
      },
      {
        label: 'Эксплуатация',
        value: 'Docker, Kubernetes, Grafana, Prometheus, GitHub Actions, Linux',
      },
    ],
    experience: [
      {
        company: 'Bereke Bank',
        role: 'Middle Golang Developer',
        period: 'Сен 2025 · настоящее время',
        context: 'Auto Loan Issuance / Единый кредитный конвейер · высокая нагрузка · event driven',
        items: [
          'Проектирую архитектуру и разрабатываю <strong>единый кредитный конвейер</strong>, унифицирующий выдачу кредитов по продуктам и централизующий маршрутизацию заявок.',
          'Реализовал множество <strong>production-интеграций</strong> с государственными и финансовыми сервисами, включая Первое кредитное бюро, реестры залогового имущества и верификацию личности.',
          'Спроектировал отказоустойчивую микросервисную архитектуру со строгими <strong>latency SLA</strong> и event-driven взаимодействием через Kafka.',
          'Сопровождал кредитный конвейер автокредитования от пилота до production: распараллелил обработку, <strong>ускорил выдачу более чем в 2,5 раза</strong>, с 40 до 15 минут, и помог вырастить поток до <strong>130 заявок в день за полгода</strong>.',
          'Разработал библиотеку алертинга в корпоративный мессенджер и операционные уведомления.',
        ],
        stack: ['Go', 'PostgreSQL', 'Redis', 'Kafka', 'Camunda BPMN', 'Docker', 'GraphQL', 'REST'],
      },
      {
        company: 'Ozon Tech',
        role: 'Junior Go Backend Engineer',
        period: 'Авг 2024 · Сен 2025',
        context: 'Платформа сотрудников · backend-команда из 3 человек · дежурства',
        items: [
          'Участвовал в проектировании разделения большого монолита примерно на <strong>10 доменных сервисов</strong>; разработал сервис данных сотрудников и сократил среднее время получения данных на <strong>25%</strong>.',
          'Единолично отвечал за backend регулярных compliance-анкет: назначение сотрудникам, уведомления и администрирование для юристов.',
          'Автоматизировал посещаемость и освобождение мест для <strong>10 тыс.+ сотрудников</strong>; на запуске платформа выдержала <strong>2 000 одновременных пользователей</strong>.',
          'Разработал backend согласования товарных знаков и генератор документов на Go; также реализовал аналитические выгрузки и превью видео для файлов до <strong>2 ТБ</strong>.',
        ],
        stack: ['Go', 'gRPC', 'PostgreSQL', 'ClickHouse', 'Redis', 'Kafka', 'Vertica', 'Grafana'],
      },
      {
        company: 'Ozon Tech',
        role: 'Go Backend Intern',
        period: 'Дек 2023 · Авг 2024',
        context: 'Корпоративная платформа найма · backend-команда из 4 человек · дежурства',
        items: [
          'Сократил p95 поиска кандидатов с <strong>1,5-2 с до 500-850 мс</strong>: исправил SQL-индексы и переписал Elasticsearch-запросы; результат подтверждён нагрузочными тестами.',
          'Спроектировал и разработал бота уведомлений об изменениях по кандидатам с надёжной отложенной доставкой через Kafka.',
          'Вошёл в ротацию дежурств, устранял накопленные production-баги и создал Grafana-дашборды для аномалий воронки и системных ошибок.',
        ],
        stack: [
          'Go',
          'PostgreSQL',
          'Redis',
          'Elasticsearch',
          'Kafka',
          'ClickHouse',
          'gRPC',
          'Grafana',
        ],
      },
    ],
    project: {
      role: 'Создатель · Backend-разработчик',
      name: 'AdalQarau',
      subtitle: 'Аналитическая платформа государственных закупок',
      period: '2024 · настоящее время',
      items: [
        'Реализовал детектирование коррупционных рисков по <strong>15 млн+ договоров</strong>, 197 тыс. заказчиков и 800 тыс. поставщиков с помощью восьми алгоритмов без обучающих данных.',
        'Система выявила <strong>448 тыс. рисковых флагов</strong> по всем 20 регионам Казахстана; пороги откалиброваны с государственными аудиторами, результаты используются в реальных проверках.',
      ],
      stack: [
        'Go',
        'ConnectRPC',
        'PostgreSQL',
        'React',
        'TypeScript',
        'MinIO/S3',
        'Docker',
        'Protobuf',
      ],
    },
    education: [
      {
        degree: 'Магистратура, Computer Science & Engineering',
        school: 'Astana IT University',
        period: '2025 · настоящее время',
        note: 'Исследование: методы обнаружения аномалий в данных тендерных закупок.',
        masters: true,
      },
      {
        degree: 'Бакалавриат, Software Engineering',
        school: 'Astana IT University',
        period: '2023 · 2025',
      },
      {
        degree: 'Предыдущее обучение',
        school: 'Университет ИТМО, Санкт-Петербург',
        period: '2021 · 2023',
        note: 'Два года обучения до перевода в AITU.',
      },
    ],
    languages: ['Русский · родной', 'Английский · C1 профессиональный', 'Казахский · базовый'],
    additional: ['Полная занятость · офис / гибрид / удалённо', 'Готов к релокации'],
  },
}
