export const personal = {
  phone: '+7 775 900-46-26',
  email: 'roman.vassilchenko.work@gmail.com',
  website: 'romanv.dev',
  github: 'github.com/RomanVassilchenko',
  linkedin: 'linkedin.com/in/rovassilchenko',
  telegram: 't.me/Roman_Vassilchenko',
}

export const resumes = {
  en: {
    name: 'Roman Vassilchenko',
    role: 'Go Backend Engineer',
    location: 'Astana, Kazakhstan · UTC+5',
    summary:
      'I build backend systems that accelerate critical business workflows and stay reliable under load, from credit pipelines at Bereke Bank to company-wide platforms at Ozon.',
    labels: {
      contacts: 'Contacts',
      impact: 'Selected impact',
      experience: 'Experience',
      toolkit: 'Production toolkit',
      education: 'Education',
      languages: 'Languages',
      additional: 'Availability',
    },
    metrics: [
      { value: '>2.5×', label: 'faster auto-loan issuance', note: '40 to 15 minutes' },
      { value: '30+', label: 'services using shared libraries', note: 'Ozon internal Go platform' },
      { value: '3×', label: 'faster candidate search', note: 'lower Elasticsearch load' },
    ],
    skills: [
      { label: 'Backend', value: 'Go, gRPC, REST/HTTP, GraphQL, Protocol Buffers' },
      { label: 'Data', value: 'PostgreSQL, Redis, ClickHouse, Vertica, Elasticsearch, MinIO/S3' },
      { label: 'Distributed', value: 'Kafka, Camunda BPMN, microservices, event-driven systems' },
      {
        label: 'Operations',
        value: 'Docker, Kubernetes, Grafana, Prometheus, GitHub Actions, Linux',
      },
    ],
    experience: [
      {
        company: 'Bereke Bank',
        role: 'Middle Golang Developer',
        period: 'Sep 2025 · Present',
        context: 'Auto Loan Issuance / Unified Credit Pipeline · high load · event driven',
        items: [
          "Architect and build the company's <strong>unified credit pipeline</strong>, standardizing loan issuance across products and centralizing application routing and validation.",
          'Built numerous <strong>production integrations</strong> with government and financial services, including First Credit Bureau, collateral registries and identity verification.',
          'Designed fault-tolerant microservice architecture with strict <strong>latency SLA</strong> and event-driven communication via Kafka.',
          'Supported the auto-loan pipeline from pilot to production: parallelized processing, made issuance <strong>more than 2.5× faster</strong>, from 40 to 15 minutes, and grew volume to <strong>130 applications per day within six months</strong>.',
          'Built a corporate messenger alerting library and operational notifications for production workflows.',
        ],
        stack: ['Go', 'PostgreSQL', 'Redis', 'Kafka', 'Camunda BPMN', 'Docker', 'GraphQL', 'REST'],
      },
      {
        company: 'Ozon Tech',
        role: 'Junior/Middle Golang Developer',
        period: 'Aug 2024 · Sep 2025',
        context: 'Employee platform · 10–15K DAU / 40K+ MAU · monolith to microservices',
        items: [
          'Helped migrate a large employee-portal monolith to microservices and reduced <strong>pod load by 20–25%</strong> within my domain.',
          'Served as the <strong>primary developer</strong> reworking internal user-data storage, office-booking workflows and corporate messenger integrations.',
          'Actively maintained <strong>internal Go libraries</strong>: built shared DB, validation and middleware components used by <strong>30+ services</strong>.',
          'Developed an automated attendance-management system for <strong>60K+ employees</strong>; the platform sustained <strong>2,000 concurrent users</strong> during rollout peaks.',
          'Engineered an ETL pipeline to Vertica, document-generation infrastructure and large-file video-preview workflows for assets up to several TB.',
        ],
        stack: ['Go', 'gRPC', 'PostgreSQL', 'ClickHouse', 'Redis', 'Kafka', 'Vertica', 'Grafana'],
      },
      {
        company: 'Ozon Tech',
        role: 'Intern/Junior Golang Developer',
        period: 'Dec 2023 · Aug 2024',
        context: 'Company-wide hiring platform · microservices · high traffic',
        items: [
          'Eliminated critical query bottlenecks in candidate ranking, delivering a <strong>significant production SQL speedup</strong> under peak load.',
          'Redesigned Elasticsearch filter execution, making search <strong>3× faster</strong> while significantly reducing cluster load.',
          'Designed a gRPC notification microservice for Mattermost with Kafka request sharding and configurable delayed dispatch.',
          'Built Grafana observability dashboards for proactive anomaly detection and faster incident response.',
        ],
        stack: [
          'Go',
          'PostgreSQL',
          'Redis',
          'Elasticsearch',
          'Kafka',
          'ClickHouse',
          'gRPC',
          'Grafana',
        ],
      },
    ],
    project: {
      role: 'Creator · Backend engineer',
      name: 'AdalQarau',
      subtitle: 'Public procurement analytics platform',
      period: '2024 · Present',
      items: [
        'Built rule-based corruption-risk detection across <strong>15M+ contracts</strong>, 197K buyers and 800K suppliers using eight indicator algorithms without labeled training data.',
        'Produced <strong>448K risk flags</strong> across all 20 regions of Kazakhstan; thresholds were calibrated with government auditors and used in real audit workflows.',
      ],
      stack: [
        'Go',
        'ConnectRPC',
        'PostgreSQL',
        'React',
        'TypeScript',
        'MinIO/S3',
        'Docker',
        'Protobuf',
      ],
    },
    education: [
      {
        degree: 'M.Sc. Computer Science & Engineering',
        school: 'Astana IT University',
        period: '2025 · Present',
        note: 'Research: intelligent methods for anomaly detection in tender procurement data.',
        masters: true,
      },
      {
        degree: 'B.Sc. Software Engineering',
        school: 'Astana IT University',
        period: '2023 · 2025',
      },
      {
        degree: 'Previous studies',
        school: 'ITMO University, St. Petersburg',
        period: '2021 · 2023',
        note: 'Two years completed before transferring to AITU.',
      },
    ],
    languages: ['Russian · Native', 'English · C1 professional', 'Kazakh · Basic'],
    additional: ['Full-time · office / hybrid / remote', 'Ready to relocate'],
  },
  ru: {
    name: 'Роман Васильченко',
    role: 'Go Backend-разработчик',
    location: 'Астана, Казахстан · UTC+5',
    summary:
      'Создаю backend-системы, которые ускоряют ключевые бизнес-процессы и стабильно работают под высокой нагрузкой: от кредитных конвейеров в Bereke Bank до корпоративных платформ Ozon.',
    labels: {
      contacts: 'Контакты',
      impact: 'Ключевые результаты',
      experience: 'Опыт работы',
      toolkit: 'Инструменты production-разработки',
      education: 'Образование',
      languages: 'Языки',
      additional: 'Формат работы',
    },
    metrics: [
      { value: '>2,5×', label: 'быстрее выдача автокредита', note: 'с 40 до 15 минут' },
      {
        value: '30+',
        label: 'сервисов используют библиотеки',
        note: 'внутренняя Go-платформа Ozon',
      },
      {
        value: '3×',
        label: 'быстрее поиск кандидатов',
        note: 'со снижением нагрузки Elasticsearch',
      },
    ],
    skills: [
      { label: 'Backend', value: 'Go, gRPC, REST/HTTP, GraphQL, Protocol Buffers' },
      { label: 'Данные', value: 'PostgreSQL, Redis, ClickHouse, Vertica, Elasticsearch, MinIO/S3' },
      {
        label: 'Распределённые системы',
        value: 'Kafka, Camunda BPMN, микросервисы, event-driven архитектура',
      },
      {
        label: 'Эксплуатация',
        value: 'Docker, Kubernetes, Grafana, Prometheus, GitHub Actions, Linux',
      },
    ],
    experience: [
      {
        company: 'Bereke Bank',
        role: 'Middle Golang Developer',
        period: 'Сен 2025 · настоящее время',
        context: 'Auto Loan Issuance / Единый кредитный конвейер · высокая нагрузка · event driven',
        items: [
          'Проектирую архитектуру и разрабатываю <strong>единый кредитный конвейер</strong>, унифицирующий выдачу кредитов по продуктам и централизующий маршрутизацию заявок.',
          'Реализовал множество <strong>production-интеграций</strong> с государственными и финансовыми сервисами, включая Первое кредитное бюро, реестры залогового имущества и верификацию личности.',
          'Спроектировал отказоустойчивую микросервисную архитектуру со строгими <strong>latency SLA</strong> и event-driven взаимодействием через Kafka.',
          'Сопровождал кредитный конвейер автокредитования от пилота до production: распараллелил обработку, <strong>ускорил выдачу более чем в 2,5 раза</strong>, с 40 до 15 минут, и помог вырастить поток до <strong>130 заявок в день за полгода</strong>.',
          'Разработал библиотеку алертинга в корпоративный мессенджер и операционные уведомления.',
        ],
        stack: ['Go', 'PostgreSQL', 'Redis', 'Kafka', 'Camunda BPMN', 'Docker', 'GraphQL', 'REST'],
      },
      {
        company: 'Ozon Tech',
        role: 'Junior/Middle Golang Developer',
        period: 'Авг 2024 · Сен 2025',
        context: 'Портал сотрудника · 10–15 тыс. DAU / 40 тыс.+ MAU · монолит в микросервисы',
        items: [
          'Участвовал в переводе большого монолита портала сотрудника на микросервисы и снизил <strong>нагрузку на pod на 20–25%</strong> в своём домене.',
          'Был <strong>основным разработчиком</strong>, отвечавшим за переработку систем хранения данных пользователей, бронирования офисов и интеграций с корпоративным мессенджером.',
          'Активно развивал <strong>внутренние Go-библиотеки</strong>: создавал общие компоненты для БД, валидации и middleware, используемые в <strong>30+ сервисах</strong>.',
          'Реализовал систему контроля посещаемости для <strong>60 тыс.+ сотрудников</strong>; платформа выдержала <strong>2 000 одновременных пользователей</strong> на пике запуска.',
          'Построил ETL-конвейер в Vertica, инфраструктуру генерации документов и обработку больших видеофайлов объёмом до нескольких ТБ.',
        ],
        stack: ['Go', 'gRPC', 'PostgreSQL', 'ClickHouse', 'Redis', 'Kafka', 'Vertica', 'Grafana'],
      },
      {
        company: 'Ozon Tech',
        role: 'Intern/Junior Golang Developer',
        period: 'Дек 2023 · Авг 2024',
        context: 'Корпоративный портал найма · микросервисы · высокая нагрузка',
        items: [
          'Устранил критические узкие места в запросах ранжирования кандидатов, добившись <strong>многократного ускорения production SQL</strong> под пиковой нагрузкой.',
          'Переработал фильтрацию Elasticsearch, <strong>ускорив поиск в 3 раза</strong> и значительно снизив нагрузку на кластер.',
          'Спроектировал gRPC-микросервис уведомлений для Mattermost с шардированием запросов через Kafka и настраиваемой отложенной отправкой.',
          'Создал Grafana-дашборды для проактивного обнаружения аномалий и сокращения времени реакции на инциденты.',
        ],
        stack: [
          'Go',
          'PostgreSQL',
          'Redis',
          'Elasticsearch',
          'Kafka',
          'ClickHouse',
          'gRPC',
          'Grafana',
        ],
      },
    ],
    project: {
      role: 'Создатель · Backend-разработчик',
      name: 'AdalQarau',
      subtitle: 'Аналитическая платформа государственных закупок',
      period: '2024 · настоящее время',
      items: [
        'Реализовал детектирование коррупционных рисков по <strong>15 млн+ договоров</strong>, 197 тыс. заказчиков и 800 тыс. поставщиков с помощью восьми алгоритмов без обучающих данных.',
        'Система выявила <strong>448 тыс. рисковых флагов</strong> по всем 20 регионам Казахстана; пороги откалиброваны с государственными аудиторами, результаты используются в реальных проверках.',
      ],
      stack: [
        'Go',
        'ConnectRPC',
        'PostgreSQL',
        'React',
        'TypeScript',
        'MinIO/S3',
        'Docker',
        'Protobuf',
      ],
    },
    education: [
      {
        degree: 'Магистратура, Computer Science & Engineering',
        school: 'Astana IT University',
        period: '2025 · настоящее время',
        note: 'Исследование: методы обнаружения аномалий в данных тендерных закупок.',
        masters: true,
      },
      {
        degree: 'Бакалавриат, Software Engineering',
        school: 'Astana IT University',
        period: '2023 · 2025',
      },
      {
        degree: 'Предыдущее обучение',
        school: 'Университет ИТМО, Санкт-Петербург',
        period: '2021 · 2023',
        note: 'Два года обучения до перевода в AITU.',
      },
    ],
    languages: ['Русский · родной', 'Английский · C1 профессиональный', 'Казахский · базовый'],
    additional: ['Полная занятость · офис / гибрид / удалённо', 'Готов к релокации'],
  },
}
